baseURL = 'https://jaime-florian.com'
languageCode = 'en-us'
title = 'Jaime Florian'
theme = 'hugo-theme-stack'

[params]
mainSections = ["projects", "blog"]
favicon = "/favicon.png"

[params.sidebar]
emoji = "ğŸ§‘ğŸ½â€ğŸš€"
subtitle = """ğŸš€ Technical Director in the 3D animation industry. Bridging art and tech
            together with code. Currently into Neovim, Rez, USD, Python, and Linux. """

[params.imageProcessing.cover]
enabled = false

[params.imageProcessing.content]
enabled = false

[[params.widgets.homepage]]
type = "search"
